blank_issues_enabled: false
contact_links:
  - name: 💬 Fazer uma Pergunta para a IA
    url: https://github.com/RenatofilhoDevandtech/RenatofilhoDevandtech/issues/new?assignees=&labels=ask-ai-assistant&template=ask-ai-assistant.md&title=Pergunta%3A+
    about: Clique aqui para fazer uma pergunta que será respondida pela IA no meu perfil.
