name: Update README Dynamically
on:
  schedule:
    # Roda a cada hora
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    # CORREÇÃO 1: Adicionando permissão de escrita no repositório
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Get Last Commit from GitHub API
        id: last_commit
        run: |
          EVENT_DATA=$(curl --silent "https://api.github.com/users/RenatofilhoDevandtech/events/public")
          REPO_NAME=$(echo "$EVENT_DATA" | jq -r '[.[] | select(.type=="PushEvent")][0].repo.name')
          COMMIT_MESSAGE=$(echo "$EVENT_DATA" | jq -r '[.[] | select(.type=="PushEvent")][0].payload.commits[0].message')
          echo "repo_full_name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT

      - name: Ask AI to improve commit message
        id: commit_suggester
        run: |
          PROMPT="Aja como um desenvolvedor sênior. Reescreva a seguinte mensagem de commit para seguir o padrão Conventional Commits (ex: 'feat(auth): Adiciona login com Google'). Seja conciso, técnico e retorne APENAS a mensagem sugerida, sem nenhum texto ou formatação adicional. A mensagem é: '${{ steps.last_commit.outputs.message }}'"
          JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" '{contents: [{parts: [{text: $prompt}]}]}')
          API_RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${{ secrets.GEMINI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD")
          SUGGESTION=$(echo "$API_RESPONSE" | jq -r '.candidates[0].content.parts[0].text' | tr -d '\n' | tr -d '`' | sed 's/\"//g')
          echo "gemini_text=$SUGGESTION" >> $GITHUB_OUTPUT

      # CORREÇÃO 2: Estrutura correta do passo final
      - name: Update README with AI Suggestion and Repo Info
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: |
            <table width="100%">
              <tr>
                <td width="20%"><b>Última Atividade em:</b></td>
                <td><a href="https://github.com/${{ steps.last_commit.outputs.repo_full_name }}"><b>${{ steps.last_commit.outputs.repo_full_name }}</b></a></td>
              </tr>
              <tr>
                <td width="20%"><b>Meu Último Commit:</b></td>
                <td><code>${{ steps.last_commit.outputs.message }}</code></td>
              </tr>
              <tr>
                <td width="20%"><b>Sugestão da IA:</b></td>
                <td><code>${{ steps.commit_suggester.outputs.gemini_text }}</code></td>
              </tr>
            </table>
